title: Anirban Saha # your name (or website title) here
logo: "/images/LinkedIN_DP.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Machine Learning Engineer with over 2 years of end-to-end experience in developing and deploying Machine Learning Models and orchestrating streaming and batch data pipelines.
  <br>
  Certified as Microsoft Azure Data Engineer, Azure Data Scientist and Azure AI Engineer.
  <br>
  I desire to be the most trusted partner by educating, investing and delivering innovative solutions that create a tangible, measurable, and attributable impact! 
  <br><br>
  If you have an opportunity that you think is perfect for me, let's connect and discuss! 
  <br><br>
  <a href="https://www.linkedin.com/in/saha-anirban8/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: G-N1XS1M4QLR # your Google Analytics tracking ID here
