title: Anirban Saha # your name (or website title) here
logo: "/images/LinkedIN_DP.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Machine Learning Engineer with over 2 years of end-to-end experience. Certified as Microsoft Azure Data Engineer, Azure Data Scientist and Azure AI Engineer.
  <br><br>
  <a href="https://www.linkedin.com/in/saha-anirban8/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-tactile
# google_analytics: G-N1XS1M4QLR # your Google Analytics tracking ID here
